name: assistants
description: A comprehensive Flutter desktop application suite with multiple assistant tools
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  
  # File System
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Process Management，执行系统命令，例如git相关操作
  # 参考：https://pub.dev/packages/process_run
  process_run: ^0.12.5+2
  
  # UI Enhancement，用于代码高亮显示
  # 参考：https://pub.dev/packages/flutter_highlight
  flutter_highlight: ^0.7.0
  syntax_highlight: ^0.3.0  # 升级到最新稳定版本
  
  # Utilities
  intl: ^0.18.1 # 用于日期格式化
  collection: ^1.17.2 # 用于集合操作
  
  # Desktop Integration
  window_manager: ^0.3.7 # 用于窗口管理，最小化、最大化、关闭窗口等
  desktop_drop: ^0.6.1 # 用于文件拖拽，在窗口中拖拽文件到应用中
  # 参考：https://pub.dev/packages/desktop_drop
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700